"""
Generate domain mappings for ALL entity names in the Scout dataset.
Outputs a TypeScript snippet to append to ENTITY_DOMAINS in connections-screen.tsx
"""
import sys, re
sys.path.insert(0, '/home/z/my-project/scripts')
from companies_dataset import COMPANIES
from convert_to_typescript import convert_company

# Get ALL unique non-country entity names
all_entities = set()
for c in COMPANIES:
    converted = convert_company(c)
    for eid, entity in converted['entities'].items():
        if entity['type'] in ('country',):
            continue
        all_entities.add(entity['name'])

# Read existing ENTITY_DOMAINS from the file
existing = set()
with open('/home/z/my-project/src/components/scout/connections-screen.tsx', 'r') as f:
    content = f.read()
    matches = re.findall(r'"([^"]+)":\s*"([^"]+)"', content)
    for key, val in matches:
        if '.' in val:
            existing.add(key)

# Generate domain mappings for ALL entities
# Strategy: match entity name to a known domain
DOMAIN_MAP = {
    # Companies in our 100-company dataset (full names)
    "ASML Holding N.V.": "asml.com",
    "AT&T Inc.": "att.com",
    "AXA S.A.": "axa.com",
    "Adidas AG": "adidas.com",
    "Airbnb, Inc.": "airbnb.com",
    "Airbus SE": "airbus.com",
    "Alibaba Group Holding Ltd.": "alibabagroup.com",
    "Allianz SE": "allianz.com",
    "Alphabet Inc. (Google)": "abc.xyz",
    "Amazon.com, Inc.": "amazon.com",
    "American Airlines Group Inc.": "aa.com",
    "Anheuser-Busch InBev SA/NV (AB InBev)": "ab-inbev.com",
    "Apple Inc.": "apple.com",
    "AstraZeneca plc": "astrazeneca.com",
    "BHP Group Ltd.": "bhp.com",
    "BYD Company Ltd.": "byd.com",
    "Banco Santander, S.A.": "santander.com",
    "Bank of America Corporation": "bankofamerica.com",
    "Bayer AG": "bayer.com",
    "Berkshire Hathaway Inc.": "berkshirehathaway.com",
    "BlackRock, Inc.": "blackrock.com",
    "Block, Inc. (Square)": "block.xyz",
    "Booking Holdings Inc.": "bookingholdings.com",
    "ByteDance Ltd. (TikTok)": "bytedance.com",
    "CATL (Contemporary Amperex Technology Co., Ltd.)": "catl.com",
    "China Mobile Ltd.": "chinamobileltd.com",
    "Coinbase Global, Inc.": "coinbase.com",
    "Costco Wholesale Corporation": "costco.com",
    "Delta Air Lines, Inc.": "delta.com",
    "Danone S.A.": "danone.com",
    "Deutsche Lufthansa AG": "lufthansagroup.com",
    "Deutsche Telekom AG": "telekom.com",
    "Domino's Pizza, Inc.": "dominos.com",
    "Electronic Arts Inc.": "ea.com",
    "Emirates Airline (Emirates Group)": "emirates.com",
    "Estée Lauder Companies Inc.": "elcompanies.com",
    "ExxonMobil Corporation": "corporate.exxonmobil.com",
    "Foxconn Technology Group (Hon Hai Precision Industry)": "foxconn.com",
    "HSBC Holdings plc": "hsbc.com",
    "H&M Hennes & Mauritz AB": "hm.com",
    "Heineken N.V.": "theheinekencompany.com",
    "Hermès International S.A.": "hermes.com",
    "Huawei Technologies Co., Ltd.": "huawei.com",
    "Inditex S.A. (Zara)": "inditex.com",
    "Inter IKEA Group": "ikea.com",
    "JPMorgan Chase & Co.": "jpmorganchase.com",
    "Johnson & Johnson": "jnj.com",
    "Kering S.A.": "kering.com",
    "L'Oréal S.A.": "loreal.com",
    "LVMH Moët Hennessy Louis Vuitton SE": "lvmh.com",
    "Lockheed Martin Corporation": "lockheedmartin.com",
    "Lululemon Athletica Inc.": "lululemon.com",
    "Marriott International, Inc.": "marriott.com",
    "McDonald's Corporation": "mcdonalds.com",
    "Mercedes-Benz Group AG": "mercedes-benz.com",
    "Meta Platforms, Inc.": "meta.com",
    "Microsoft Corporation": "microsoft.com",
    "Mondelez International, Inc.": "mondelezinternational.com",
    "NVIDIA Corporation": "nvidia.com",
    "Nestlé S.A.": "nestle.com",
    "Netflix, Inc.": "netflix.com",
    "Nike, Inc.": "nike.com",
    "Nintendo Co., Ltd.": "nintendo.com",
    "Novo Nordisk A/S": "novonordisk.com",
    "PepsiCo, Inc.": "pepsico.com",
    "Pfizer Inc.": "pfizer.com",
    "PetroChina Company Ltd.": "petrochina.com.cn",
    "Ping An Insurance Group Co. of China": "pingan.com",
    "Procter & Gamble Co.": "pg.com",
    "RTX Corporation (Raytheon Technologies)": "rtx.com",
    "Ryanair Holdings plc": "ryanair.com",
    "Roche Holding AG": "roche.com",
    "Saudi Aramco": "aramco.com",
    "Shell plc": "shell.com",
    "Sony Group Corporation": "sony.com",
    "Spotify Technology S.A.": "spotify.com",
    "Starbucks Corporation": "starbucks.com",
    "Take-Two Interactive Software, Inc.": "take2games.com",
    "Target Corporation": "target.com",
    "Tesla, Inc.": "tesla.com",
    "The Boeing Company": "boeing.com",
    "The Coca-Cola Company": "coca-colacompany.com",
    "The Walt Disney Company": "thewaltdisneycompany.com",
    "TotalEnergies SE": "totalenergies.com",
    "Toyota Motor Corporation": "global.toyota",
    "Uber Technologies, Inc.": "uber.com",
    "Unilever PLC": "unilever.com",
    "Vodafone Group plc": "vodafone.com",
    "Volkswagen Group": "volkswagenag.com",
    "Walmart Inc.": "walmart.com",
    "Warner Bros. Discovery, Inc.": "wbd.com",
    "Wells Fargo & Company": "wellsfargo.com",
    "Verizon Communications Inc.": "verizon.com",
    "Yum! Brands, Inc.": "yum.com",

    # Companies NOT in dataset but mentioned as suppliers/investors
    "AMD (US)": "amd.com",
    "ASML (Netherlands)": "asml.com",
    "BAE Systems (UK)": "baesystems.com",
    "Berkshire Hathaway (Warren Buffett)": "berkshirehathaway.com",
    "Berkshire Hathaway (self-held via repurchase)": "berkshirehathaway.com",
    "Berkshire Hathaway Energy (own subsidiary)": "berkshirehathawayenergy.com",
    "BioNTech (Germany)": "biontech.de",
    "BlackRock (treasury / self-held)": "blackrock.com",
    "Boeing (737 MAX, 787)": "boeing.com",
    "Boeing (737-800, 737 MAX 8200)": "boeing.com",
    "Boeing (777, 787)": "boeing.com",
    "Boeing (787, 777)": "boeing.com",
    "Boeing / Airbus": "boeing.com",
    "Boeing 737 MAX delays": "boeing.com",
    "Bosch (Germany)": "bosch.com",
    "Bloomberg / Refinitiv": "bloomberg.com",
    "Broadcom": "broadcom.com",
    "CFM International (GE/Safran)": "cfmaeroengines.com",
    "Cisco, Juniper": "cisco.com",
    "Coca-Cola Consolidated (US)": "cokeconsolidated.com",
    "Coca-Cola Europacific Partners (UK)": "cceptruck.com",
    "Coca-Cola FEMSA (Mexico)": "coca-colafemsa.com",
    "Coca-Cola HBC (Switzerland/Greece)": "coca-colahbc.com",
    "Coca-Cola, P&G, Kraft Heinz, etc.": "coca-cola.com",
    "Continental (Germany)": "continental.com",
    "CrowdStrike / Microsoft Azure": "crowdstrike.com",
    "Cymer (US, ASML subsidiary)": "asml.com",
    "DICE, BioWare, Respawn (own studios)": "ea.com",
    "Denso (Japan, Toyota affiliate)": "denso.com",
    "Ericsson, Nokia": "ericsson.com",
    "Ericsson, Nokia, Huawei (legacy, phasing out)": "ericsson.com",
    "Ericsson, Nokia, Huawei (limited)": "ericsson.com",
    "Ericsson, Nokia, Samsung": "ericsson.com",
    "FEMSA (Mexico)": "femsa.com",
    "FIFA / FIFPro (historic)": "fifa.com",
    "FIS, Fiserv": "fisglobal.com",
    "FIS, Fiserv, Jack Henry": "fisglobal.com",
    "First Solar, SunPower": "firstsolar.com",
    "Foxconn / Asian electronics": "foxconn.com",
    "Foxconn / Hon Hai (TW/CN/IN)": "foxconn.com",
    "Foxconn / Hon Hai (Taiwan)": "foxconn.com",
    "GE / Rolls-Royce / Pratt & Whitney": "ge.com",
    "GE Aerospace (US)": "geaerospace.com",
    "GE Aerospace / CFM (US/France)": "geaerospace.com",
    "Geico (own subsidiary)": "geico.com",
    "Genentech (US subsidiary)": "gene.com",
    "Glencore (Switzerland)": "glencore.com",
    "Glencore plc": "glencore.com",
    "Google Cloud": "cloud.google.com",
    "Huawei / Alibaba Cloud": "huawei.com",
    "Huawei Investment & Holding Trade Union Committee": "huawei.com",
    "Huawei, ZTE (Chinese)": "huawei.com",
    "Index providers (MSCI, FTSE Russell)": "msci.com",
    "Intel (US)": "intel.com",
    "KKR / Mubadala / ADIA / Silver Lake / General Atlantic": "kkr.com",
    "KLA (US)": "kla.com",
    "Lam Research (US)": "lamresearch.com",
    "LG Energy Solution (South Korea)": "lgensol.com",
    "LVMH (Arnault)": "lvmh.com",
    "Lactalis (French dairy)": "lactalis.fr",
    "Logistics (DHL, Maersk)": "dhl.com",
    "Logistics (Maersk, DHL)": "maersk.com",
    "Logistics (Maersk, FedEx)": "fedex.com",
    "Logistics (own fleet)": "logistics.com",
    "Logistics (ports, rail, shipping)": "maersk.com",
    "Logistics (shipping, air)": "dhl.com",
    "Logistics (truck, rail)": "dhl.com",
    "MTU Aero Engines (Germany)": "mtu.de",
    "Maersk / shipping companies": "maersk.com",
    "Marmon, Lubrizol, IMC (own subsidiaries)": "berkshirehathaway.com",
    "Mining equipment (Caterpillar, Komatsu)": "caterpillar.com",
    "Morgan Stanley": "morganstanley.com",
    "NFL, NBA, NHL, UFC": "nfl.com",
    "Naspers / Prosus (South Africa)": "naspers.com",
    "National Pension Service of Korea": "nps.or.kr",
    "Norges Bank (Norway SWF)": "nbim.no",
    "Norges Bank Investment Management (Norway SWF)": "nbim.no",
    "Northvolt (Sweden, VW-backed)": "northvolt.com",
    "Novartis": "novartis.com",
    "Novo Nordisk Foundation": "novonordiskfonden.dk",
    "NVIDIA / Qualcomm": "nvidia.com",
    "Oracle (US)": "oracle.com",
    "Pegatron (Taiwan)": "pegatron.com",
    "Ping An Insurance (China)": "pingan.com",
    "Pratt & Whitney (RTX)": "prattwhitney.com",
    "Pratt & Whitney (RTX, US)": "prattwhitney.com",
    "Pratt & Whitney internal": "prattwhitney.com",
    "Q-Power / PowerCo (VW subsidiary)": "volkswagenag.com",
    "Qualcomm (US)": "qualcomm.com",
    "Raytheon (RTX)": "rtx.com",
    "Real estate REITs (Host Hotels, Sunstone)": "hosthotels.com",
    "Reinsurers (Munich Re, Swiss Re, Hannover Re)": "munichre.com",
    "Reliance Industries (Mukesh Ambani parent)": "ril.com",
    "Reliance Jio Platforms (Jio)": "jio.com",
    "Rockstar studios (own)": "rockstargames.com",
    "Rolls-Royce (UK)": "rolls-royce.com",
    "Rolls-Royce / GE / Engine Alliance": "rolls-royce.com",
    "Rolls-Royce / GE / Pratt & Whitney": "rolls-royce.com",
    "Russian nickel (Nornickel)": "nornickel.com",
    "SEPI (Spain)": "sepies.es",
    "SOGEPA (France)": "sogepa.fr",
    "Safran (France)": "safran-group.com",
    "Samsung / Micron": "samsung.com",
    "Samsung C&T (affiliate)": "samsungcnt.com",
    "Samsung Electronics Co., Ltd.": "samsung.com",
    "Saudi Arabia PIF": "pif.gov.sa",
    "Schlumberger (legacy)": "slb.com",
    "Sequoia Capital (US/China)": "sequoiacap.com",
    "Shin-Etsu (Japan)": "shinetsu.co.jp",
    "Software (SAP, Oracle)": "sap.com",
    "Sony (Japan)": "sony.com",
    "Sony / Microsoft / Nintendo": "sony.com",
    "Sony / Omnivision": "sony.com",
    "Sony Music Entertainment": "sonymusic.com",
    "Sony Semiconductor (own subsidiary)": "sony-semicon.com",
    "Spirit AeroSystems (US/UK/Belfast)": "spiritaero.com",
    "Spirit AeroSystems (formerly Boeing subsidiary)": "spiritaero.com",
    "Sports leagues": "nfl.com",
    "Sports leagues (NFL, NBA, etc.)": "nfl.com",
    "Stripe / payment processors": "stripe.com",
    "Susquehanna International (US)": "sig.com",
    "Swiss watchmakers": "tagheuer.com",
    "Swiss watchmakers (Girard-Perregaux, Ulysse Nardin)": "girard-perregaux.com",
    "TSMC (Taiwan Semiconductor Manufacturing Company)": "tsmc.com",
    "TSMC (Taiwan, pre-2020)": "tsmc.com",
    "TSMC (via AMD, NVIDIA)": "tsmc.com",
    "TSMC (via Annapurna Labs)": "tsmc.com",
    "Taiwan government (National Development Fund)": "ndc.gov.tw",
    "Tech (Oracle Hospitality, Sabre)": "sabre.com",
    "TechnipFMC, McDermott": "technipfmc.com",
    "Tencent Holdings": "tencent.com",
    "Tencent Holdings Ltd.": "tencent.com",
    "Tencent subsidiary (TCM)": "tencent.com",
    "The Master Trust Bank of Japan": "mtb.jp",
    "Japan Trustee Services Bank": "tsb.jp",
    "Tokyo Electron (Japan)": "tel.com",
    "Trumpf (Germany)": "trumpf.com",
    "Universal Music Group": "universalmusic.com",
    "VDL (Netherlands)": "vdlgroep.nl",
    "Vestas, Siemens Gamesa": "vestas.com",
    "Visa / Mastercard": "visa.com",
    "Visa / Mastercard / UnionPay": "visa.com",
    "Voice / motion capture actors (SAG-AFTRA)": "sagaftra.org",
    "Warner Music Group": "wmg.com",
    "Western technology providers": "intel.com",
    "Wells Fargo & Company": "wellsfargo.com",
    "Wood suppliers (Poland, Sweden, Russia historic)": "ikea.com",
    "Yeezy inventory (sold down 2023-2024)": "adidas.com",
    "Zeiss (Germany)": "zeiss.com",
    "a16z (Andreessen Horowitz)": "a16z.com",
    "Albemarle (US)": "albemarle.com",
    "Applied Materials (US)": "amat.com",
    "Asset custodians (State Street, BNY)": "statestreet.com",
    "Bloomberg / Refinitiv": "bloomberg.com",
    "BNP Paribas": "bnpparibas.com",
    "Botín family": "santander.com",
    "Cargill / Tate & Lyle": "cargill.com",
    "Catalent, Lonza (CDMOs)": "catalent.com",
    "Caterpillar / Cummins": "caterpillar.com",
    "Caterpillar, Cummins": "caterpillar.com",
    "Cheese suppliers (Leprino — exclusive)": "leprinofoods.com",
    "Cheese suppliers (Leprino)": "leprinofoods.com",
    "Chemical companies (BASF, Dow)": "basf.com",
    "Chemical companies (BASF, Givaudan, Firmenich)": "basf.com",
    "Chemical companies (Givaudan, Firmenich, IFF)": "givaudan.com",
    "Chemical suppliers (BASF, Lanxess)": "basf.com",
    "Chicken suppliers (Tyson, Pilgrim's)": "tysonfoods.com",
    "Cloud / data center providers": "aws.amazon.com",
    "Cloud / tech providers (AWS)": "aws.amazon.com",
    "Cloud providers (AWS, Azure)": "aws.amazon.com",
    "Cloud providers (AWS, Microsoft Azure)": "aws.amazon.com",
    "Cloud providers (AWS, Microsoft Azure, IBM)": "aws.amazon.com",
    "Cold chain logistics": "dhl.com",
    "Collins Aerospace internal": "collinsaerospace.com",
    "Consulting firms (Deloitte, PwC, Accenture)": "deloitte.com",
    "Content studios (Sony, Disney, Viacom)": "sony.com",
    "Contract manufacturers": "foxconn.com",
    "Custodian banks (State Street, BNY Mellon, JPMorgan)": "statestreet.com",
    "Data vendors (Bloomberg, Refinitiv)": "bloomberg.com",
    "Dubai Airports": "dubaiairports.ae",
    "Engines (GE, RR, Pratt)": "ge.com",
    "Explosives suppliers (Orica, Orica)": "orica.com",
    "Fiber optic cable suppliers (Corning, Prysmian)": "corning.com",
    "Glass vial suppliers (Corning, Schott)": "corning.com",
    "Halliburton (legacy)": "halliburton.com",
    "Halliburton, Schlumberger, Baker Hughes": "halliburton.com",
    "IHI": "ihi.co.jp",
    "Host Hotels": "hosthotels.com",
    "Sunstone": "sunstonehotels.com",
    "Oracle Hospitality": "oracle.com",
    "Sabre": "sabre.com",
    "Identity verification providers": "onfido.com",
    "Independent production companies": "imdb.com",
    "Internet service providers": "comcast.com",
    "Major consulting firms": "mckinsey.com",
    "Music rights holders": "ascap.com",
    "Oil suppliers ( UAE refining)": "adnoc.ae",
    "Packaging suppliers": "tetrapak.com",
    "Packaging suppliers (glass, plastic)": "tetrapak.com",
    "Palm oil derivatives": "palmoil.org",
    "Panasonic (Japan)": "panasonic.com",
    "Perfumers (Grasse, France)": "givaudan.com",
    "Petrochemical companies": "basf.com",
    "Pharmaceutical ingredients": "sigmaaldrich.com",
    "Property management software": "guesty.com",
    "Refineries": "exxonmobil.com",
    "Refineries (Delta owns Trainer refinery)": "delta.com",
    "Refineries / oil companies": "exxonmobil.com",
    "Reinsurers (Munich Re, Swiss Re, Hannover Re)": "munichre.com",
    "Russian timber (historic, now sanctioned)": "ikea.com",
    "Samsung": "samsung.com",
    "Samsung (South Korea)": "samsung.com",
    "SAP, Oracle": "sap.com",
    "Specialty metals suppliers (titanium, etc.)": "timet.com",
    "State-owned power utilities": "edf.fr",
    "Sterile packaging suppliers": "steris.com",
    "Sugar suppliers (global)": "tateandlyle.com",
    "Thailand / Indonesia": "foxconn.com",
    "Theme park construction firms": "disney.com",
    "Thousands of CPG manufacturers": "pg.com",
    "Thousands of sub-tier suppliers": "lockheedmartin.com",
    "Thousands of sub-tier suppliers (quality issues)": "boeing.com",
    "Tomato suppliers": "kraftheinz.com",
    "Trading infrastructure providers": "swift.com",
    "U.S. trucking companies": "ups.com",
    "Various equipment vendors": "cisco.com",
    "Various manufacturing contractors": "foxconn.com",
    "Vietnam / Indonesia / Cambodia": "foxconn.com",
    "Visa / Mastercard": "visa.com",
    "Water utilities": "veolia.com",
    "Wine / spirits producers": "pernod-ricard.com",

    # People — map to their company domain
    "Amancio Ortega (via Pontegadea)": "inditex.com",
    "Arnault family (via Christian Dior SE)": "lvmh.com",
    "Bettencourt family (via Téthys)": "loreal.com",
    "Brian Armstrong (founder/CEO)": "coinbase.com",
    "Chip Wilson (founder)": "lululemon.com",
    "Daniel Ek (founder/CEO)": "spotify.com",
    "Elon Musk (founder/CEO)": "tesla.com",
    "Hoffmann / Oeri founding family": "roche.com",
    "Ivan Glasenberg (former CEO)": "glencore.com",
    "Jack Dorsey (founder)": "block.xyz",
    "Jack Ma (founder)": "alibabagroup.com",
    "Jeff Bezos (founder)": "amazon.com",
    "Jensen Huang (founder/CEO)": "nvidia.com",
    "Larry Page & Sergey Brin (founders)": "abc.xyz",
    "Lauder family": "elcompanies.com",
    "Lee family (founding)": "samsung.com",
    "Mark Zuckerberg (founder/CEO)": "meta.com",
    "Mingzhe Ma (founder)": "pingan.com",
    "Phil Knight (founder) + family": "nike.com",
    "Pinault family (via Artemis Group)": "kering.com",
    "Pony Ma (founder/CEO)": "tencent.com",
    "Porsche SE (Porsche/Piëch family)": "porsche.de",
    "Ren Zhengfei (founder)": "huawei.com",
    "Robin Zeng (founder/CEO)": "catl.com",
    "Rosalia Mera ( Sandra Ortega Mera, daughter)": "inditex.com",
    "Terry Gou (founder)": "foxconn.com",
    "Walton family (via Walton Enterprises LLC)": "walmart.com",
    "Wang Chuanfu (founder/CEO)": "byd.com",
    "Botín family": "santander.com",
    "Persson family (via Ramsbury Invest)": "hm.com",
    "Heineken family (via L'Arche Green Investment / Stichting)": "theheinekencompany.com",
    "Hermès / Dumas family (via H51 SAS)": "hermes.com",
    "Belgian São Paulo families (Stichting), including Sicupira/Telles/Lemann": "ab-inbev.com",

    # Investors / funds
    "Baillie Gifford": "bailliegifford.com",
    "Capital Research Group": "capgroup.com",
    "General Atlantic": "generalatlantic.com",
    "Geode Capital": "geodecapital.com",
    "Kennedy Wilson Holdings": "kennedywilson.com",
    "KKR": "kkr.com",
    "Newport Trust": "newporttrust.com",
    "PRIMECAP Management": "primecap.com",
    "Renaissance Technologies": "rentec.com",
    "Susquehanna International (US)": "sig.com",
    "T. Rowe Price": "troweprice.com",
    "Union Square Ventures": "usv.com",
    "Wellington Management": "wellington.com",
    "Qatar Holding": "qia.qa",
    "Qatar Investment Authority": "qia.qa",
    "Kuwait Investment Authority": "kia.gov.kw",
    "Singapore GIC": "gic.com.sg",
    "Mubadala": "mubadala.com",
    "ADIA": "adia.ae",
    "Silver Lake": "silverlake.com",
    "SoftBank (Japan)": "softbank.com",
    "Altria": "altria.com",
    "Allianz Global Investors": "allianzgi.com",
    "BNP Paribas": "bnpparibas.com",
    "Charter Life (formerly HSBC stake)": "hsbc.com",
    "Foreign institutional investors": "blackrock.com",
    "HSBC Custody Nominees": "hsbc.com",
    "Morgan Stanley": "morganstanley.com",
    "Naspers / Prosus (South Africa)": "naspers.com",
    "Other institutional": "blackrock.com",
    "Peugeot family (via Peugeot Invest)": "peugeot.com",
    "Ping An Insurance (China)": "pingan.com",
    "Public float": "marketwatch.com",
    "Public float (B shares)": "marketwatch.com",
    "Public float (B-shares)": "marketwatch.com",
    "Public float (Class A)": "marketwatch.com",
    "Public float (HK + Shanghai)": "marketwatch.com",
    "Public float (HK)": "marketwatch.com",
    "Public float (Shenzhen)": "marketwatch.com",
    "Public float (Tadawul)": "marketwatch.com",
    "Public shareholders": "marketwatch.com",
    "Saudi public / institutions": "aramco.com",
    "Shanghai public": "marketwatch.com",
    "Hong Kong public": "marketwatch.com",
    "Taiwan domestic institutions": "marketwatch.com",
    "Swiss pension funds": "ubs.com",
    "No external investors": "crunchbase.com",
    "No public shareholders": "crunchbase.com",
    "Employees / founders": "linkedin.com",

    # Government entities
    "GZBV (Germany, via KfW)": "kfw.de",
    "Shenzhen Investment Holdings (state-owned)": "sdi.gov.cn",
    "BAIC (China, state-owned)": "baicmotor.com",
    "CNPC (state-owned parent)": "cnpc.com.cn",
    "China Mobile Communications Group (state-owned parent)": "chinamobileltd.com",
    "Ningde SASAC (state asset)": "sasac.gov.cn",
    "China (CCP)": "gov.cn",

    # Generic supplier categories — map to industry associations
    "ABC affiliates": "abc.com",
    "Agricultural ingredients (botanicals)": "stevia.com",
    "Agricultural producers": "fao.org",
    "Airlines (legacy + LCC)": "iata.org",
    "Airports": "aci.aero",
    "Airports (Frankfurt, Munich)": "fraport.com",
    "Airports (secondary, low-cost)": "aci.aero",
    "Alibaba Cloud / Tencent Cloud": "alibabacloud.com",
    "Aluminium / PET suppliers": "ball.com",
    "Aluminium can suppliers": "ball.com",
    "Apparel manufacturers (Asia)": "gap.com",
    "API suppliers (Denmark, EU)": "novonordisk.com",
    "API suppliers (global)": "sigmaaldrich.com",
    "Barley / hop farmers (global)": "beerbrewers.eu",
    "Beef suppliers (Cargill, JBS)": "cargill.com",
    "Bottled water sources (Evian, Volvic)": "danone.com",
    "C.A.F.E. Practices network (~400K farmers)": "starbucks.com",
    "CDMOs": "catalent.com",
    "CDMOs (Catalent, Lonza)": "catalent.com",
    "CPG manufacturers": "pg.com",
    "Cable / satellite / streaming": "comcast.com",
    "Cable networks": "comcast.com",
    "California": "ca.gov",
    "California / New York": "ca.gov",
    "Canada": "canada.ca",
    "Car rental companies": "hertz.com",
    "Cashmere / wool suppliers": "lvmh.com",
    "Cell culture media suppliers": "thermofisher.com",
    "Component suppliers (Asia)": "foxconn.com",
    "Corn suppliers (US Midwest)": "cargill.com",
    "Cotton suppliers (global)": "cotton.org",
    "Cotton suppliers (global, non-Xinjiang)": "cotton.org",
    "Cotton suppliers (non-Xinjiang)": "cotton.org",
    "Crypto custody providers (own)": "coinbase.com",
    "Dairy suppliers (global)": "danone.com",
    "Device component suppliers": "foxconn.com",
    "Diagnostics reagent suppliers": "thermofisher.com",
    "Diamond and precious stone suppliers (global)": "tiffany.com",
    "Domestic Chinese": "huawei.com",
    "Domestic Chinese service companies": "alibaba.com",
    "Domestic IT vendors": "huawei.com",
    "Domestic Saudi industrial base": "aramco.com",
    "Domestic U.S. service companies": "ibm.com",
    "Domestic chipmakers": "smic.com",
    "Domestic cloud vendors": "alibabacloud.com",
    "Domestic server makers": "inspur.com",
    "Domestic steel / equipment": "baosteel.com",
    "Domestic suppliers": "alibaba.com",
    "Drivers (gig workers)": "uber.com",
    "Electrolyte / separator suppliers": "catl.com",
    "Energy suppliers": "edf.fr",
    "Energy suppliers (gas, electricity)": "edf.fr",
    "Engineering contractors": "bechtel.com",
    "Explosives suppliers": "orica.com",
    "Fiber optic cable suppliers": "corning.com",
    "Food / beverage suppliers": "nestle.com",
    "Franchisees": "mcdonalds.com",
    "Franchisees (independent + master)": "mcdonalds.com",
    "Franchisees (property owners)": "marriott.com",
    "French ateliers": "lvmh.com",
    "French leather artisans (own ateliers)": "lvmh.com",
    "French vineyards (Champagne, Cognac)": "lvmh.com",
    "Gasoline suppliers": "shell.com",
    "Glass / packaging suppliers": "corning.com",
    "Glass / plastic suppliers": "corning.com",
    "Glass / metal suppliers": "corning.com",
    "Glass bottle suppliers": "corning.com",
    "Glass vial suppliers": "corning.com",
    "Gold / diamond suppliers": "tiffany.com",
    "Hosts (5M+)": "airbnb.com",
    "Hotels / properties (2M+)": "booking.com",
    "Italian leather artisans (Tuscany)": "lvmh.com",
    "Jewellery suppliers": "tiffany.com",
    "Jio Platforms (own subsidiary)": "jio.com",
    "Kirkland Signature (own brand)": "costco.com",
    "Linens / amenities suppliers": "marriott.com",
    "Logistics providers": "dhl.com",
    "Medical device component suppliers": "medtronic.com",
    "Oil suppliers (UAE refining)": "adnoc.ae",
    "Owned brand suppliers (Good & Gather, etc.)": "target.com",
    "Owned store properties": "walmart.com",
    "Packaging suppliers": "tetrapak.com",
    "Palm oil derivatives": "unilever.com",
    "Petrochemical companies": "basf.com",
    "Pharmaceutical ingredients": "sigmaaldrich.com",
    "Plastic packaging suppliers": "tetrapak.com",
    "Polyester / synthetic fibre suppliers": "unilever.com",
    "Potato growers (US, EU)": "simplot.com",
    "Production studios (own + third-party)": "disney.com",
    "Real estate developers": "related.com",
    "Refineries": "exxonmobil.com",
    "Refineries / oil companies": "exxonmobil.com",
    "Retail suppliers": "walmart.com",
    "Silk / fabric suppliers": "lvmh.com",
    "Silk producers (Italy, France)": "lvmh.com",
    "Silk producers (Lyon, France)": "lvmh.com",
    "Spanish / Portuguese / Moroccan textile factories": "inditex.com",
    "State-owned power utilities": "edf.fr",
    "Sterile packaging suppliers": "steris.com",
    "Sugar suppliers (global)": "tateandlyle.com",
    "Synthetic fibre suppliers": "unilever.com",
    "Synthetic fibre suppliers (Luon, Nulu fabrics)": "lululemon.com",
    "Telco partners globally": "verizon.com",
    "Theme park construction firms": "disney.com",
    "Thousands of CPG manufacturers": "pg.com",
    "Thousands of sub-tier suppliers": "lockheedmartin.com",
    "Thousands of sub-tier suppliers (quality issues)": "boeing.com",
    "Tomato suppliers": "kraftheinz.com",
    "U.S. trucking companies": "ups.com",
    "Various equipment vendors": "cisco.com",
    "Various manufacturing contractors": "foxconn.com",
    "Vietnam / Indonesia / Cambodia": "foxconn.com",
    "Wheat / flour suppliers": "cargill.com",
    "Wheat suppliers": "cargill.com",
    "Wine / spirits producers": "pernod-ricard.com",
    "Wood suppliers (Poland, Sweden, Russia historic)": "ikea.com",

    # Regions/multi-country
    "Asia": "un.org",
    "Australia / South Africa": "un.org",
    "Austria / Belgium / Italy": "europa.eu",
    "Bangladesh / India / China": "un.org",
    "Bangladesh / Turkey": "un.org",
    "Brazil": "gov.br",
    "Côte d'Ivoire / Ghana": "un.org",
    "France / California": "europa.eu",
    "Indonesia / Malaysia": "un.org",
    "Iraq": "gov.iq",
    "Israel, UAE": "un.org",
    "Japan, Australia, South Korea": "un.org",
    "Japan, South Korea": "un.org",
    "Myanmar / Ethiopia": "un.org",
    "Russia": "gov.ru",
    "Saudi Arabia, UAE": "un.org",
    "South Africa": "gov.za",
    "South Korea": "korea.kr",
    "Thailand / Indonesia": "un.org",
    "Vietnam": "gov.vn",
    "Vietnam / Indonesia / Cambodia": "un.org",
    "China / Russia": "un.org",
    "Germany": "bund.de",
    "India": "gov.in",
    "Japan": "go.jp",
    "California": "ca.gov",
    "Florida": "fl.gov",
    "Minnesota": "mn.gov",
    "New York City": "nyc.gov",
    "Paris": "paris.fr",
    "Canada": "canada.ca",
    "United Kingdom": "gov.uk",
    "United States": "whitehouse.gov",
    "European Union": "europa.eu",
    "European Union (EASA)": "easa.europa.eu",
    "OPEC+ members": "opec.org",
    "NATO allies": "nato.int",
    "Government of Saudi Arabia (PIF)": "pif.gov.sa",
    "Government of Dubai (via ICD)": "icd.gov.ae",
    "German government (KfW)": "kfw.de",
    "German government (via KfW)": "kfw.de",
    "State of Lower Saxony (Germany)": "niedersachsen.de",
    "U.S. Federal Government": "whitehouse.gov",
    "United States (DoD)": "defense.gov",
    "United States (FAA)": "faa.gov",
    "United States (Fed, OCC, CFPB)": "federalreserve.gov",
    "United States (Fed, OCC, FDIC, CFPB)": "federalreserve.gov",
    "United States (Federal Reserve, OCC, FDIC, CFPB)": "federalreserve.gov",
    "United States (State Department)": "state.gov",
    "China (CCP)": "gov.cn",
    "CNPC (state-owned parent)": "cnpc.com.cn",
    "China Mobile Communications Group (state-owned parent)": "chinamobileltd.com",
    "Ningde SASAC (state asset)": "sasac.gov.cn",
    "BAIC (China, state-owned)": "baicmotor.com",
    "GZBV (Germany, via KfW)": "kfw.de",
    "Shenzhen Investment Holdings (state-owned)": "sdi.gov.cn",
    "Saudi Arabia": "gov.sa",
    "Saudi Arabia PIF": "pif.gov.sa",
    "SOGEPA (France)": "sogepa.fr",
    "SEPI (Spain)": "sepies.es",
    "Taiwan government (National Development Fund)": "ndc.gov.tw",
    "National Pension Service of Korea": "nps.or.kr",
    "Norges Bank (Norway SWF)": "nbim.no",
    "Norges Bank Investment Management (Norway SWF)": "nbim.no",
    "Novo Nordisk Foundation": "novonordiskfonden.dk",
    "Stichting IKEA Foundation": "ikeafoundation.org",
    "Stichting INGKA Foundation": "ingka.com",
    "Inter IKEA Holding (Netherlands)": "ikea.com",
    "Huawei Investment & Holding Trade Union Committee": "huawei.com",
    "Belgian São Paulo families (Stichting), including Sicupira/Telles/Lemann": "ab-inbev.com",
    "Heineken family (via L'Arche Green Investment / Stichting)": "theheinekencompany.com",
    "Hermès / Dumas family (via H51 SAS)": "hermes.com",
    "L'Arche Green Investment": "hermes.com",
    "H2 SAS": "hermes.com",
    "Pontegadea": "pontegadea.com",
    "Ramsbury Invest": "hm.com",
    "Charter Life (formerly HSBC stake)": "hsbc.com",
    "Lactalis (French dairy)": "lactalis.fr",
    "Walton family (via Walton Enterprises LLC)": "walmart.com",
    "Walton Enterprises": "walmart.com",
    "The Master Trust Bank of Japan": "mtb.jp",
    "Japan Trustee Services Bank": "tsb.jp",
    "HSBC Custody Nominees": "hsbc.com",
    "Berkshire Hathaway (Warren Buffett)": "berkshirehathaway.com",
    "Berkshire Hathaway (self-held via repurchase)": "berkshirehathaway.com",
    "Berkshire Hathaway Energy (own subsidiary)": "berkshirehathawayenergy.com",
    "Berkshire Hathaway Inc.": "berkshirehathaway.com",
    "Marmon, Lubrizol, IMC (own subsidiaries)": "berkshirehathaway.com",
    "Geico (own subsidiary)": "geico.com",
    "BNSF Railway (own subsidiary)": "bnsf.com",
    "Genentech (US subsidiary)": "gene.com",
    "Rockstar studios (own)": "rockstargames.com",
    "Sony Semiconductor (own subsidiary)": "sony-semicon.com",
    "Sony Music Entertainment": "sonymusic.com",
    "Universal Music Group": "universalmusic.com",
    "Warner Music Group": "wmg.com",
    "Q-Power / PowerCo (VW subsidiary)": "volkswagenag.com",
    "Jio Platforms (own subsidiary)": "jio.com",
    "Kirkland Signature (own brand)": "costco.com",
    "Self-supplied (vertical)": "linkedin.com",
    "Crypto custody providers (own)": "coinbase.com",
    "Yeezy inventory (sold down 2023-2024)": "adidas.com",
    "CrowdStrike / Microsoft Azure": "crowdstrike.com",
    "Boeing 737 MAX delays": "boeing.com",
    "Russian nickel (Nornickel)": "nornickel.com",
    "Russian timber (historic, now sanctioned)": "ikea.com",
}

# Generate the TypeScript entries
lines = []
for name in sorted(DOMAIN_MAP.keys()):
    domain = DOMAIN_MAP[name]
    # Escape any quotes in the name
    escaped = name.replace('"', '\\"')
    lines.append(f'  "{escaped}": "{domain}",')

print(f"Generated {len(lines)} domain mappings")
# Write to a temp file
with open('/tmp/entity_domains_ts.txt', 'w') as f:
    f.write('\n'.join(lines))
